version: '3.9'
services:
  main:
    image: farzadjambor/carshenas:latest
    restart: always
    ports:
      - "84:80"

  development:
    image: sadeq76/carshenas:latest
    restart: always
    ports:
      - "83:80"
