version: '3.9'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "84:80"

  development:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "83:80"
