name: Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build
        run: docker build .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 5
    steps:
      - name: Run Command for Main Branch
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command_timeout: 5m
          script: carshenas-frontend/deploy.sh main
        if: github.ref == 'refs/heads/main'

      - name: Run Command for Development Branch
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command_timeout: 5m
          script: carshenas-frontend/deploy.sh development
        if: github.ref == 'refs/heads/development'
